apiVersion: v1
kind: Service
metadata:
  name: frontend-load-balancer-service
spec:
  type: {{.Values.service.type}}
  ports:
  - port: 90
    targetPort: {{.Values.container.port}}
  selector:
    component: {{.Values.name}} 
